
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctm_clean_scene = { path = "../game", default-features = false }

[features]
default = ["ctm_clean_scene/default"]
dylib-engine = ["ctm_clean_scene/dylib-engine"]
