
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
ctm_clean_scene = { path = "../game", optional = true }

[features]
default = ["ctm_clean_scene"]
dylib = ["fyrox/dylib"]
